[project]
name = "dcascade-py"
version = "2.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "geopandas==1.1.1",
    "matplotlib>=3.10.8",
    "networkx==3.5",
    "numpy==2.3.2",
    "openpyxl>=3.1.5",
    "pandas==2.3.1",
    "scipy>=1.16.3",
    "shapely>=2.1.2",
    "tqdm>=4.67.1",
    "PyQt6",
    "PyQt6-WebEngine",
    "folium",
    "plotly",
    "pydantic",
    "qt-material",
    "mapclassify",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "ruff",
]

[tool.ruff]
exclude = [
    "src",
    "user_scripts",
    "unit_tests",
    "post_process_examples",
    "json_runner",
    "inputs",
    "docs",
]
line-length = 120
