# setup_qgis_environment.ps1
# Creates a dedicated Python environment with exact dependencies from pyproject.toml
# and configures it for use with QGIS

$ErrorActionPreference = "Stop"

$profileName = "dcascade-testing"
$envName = "dcascade-qgis-env"

Write-Host "============================================" -ForegroundColor Cyan
Write-Host "Q-Cascade QGIS Environment Setup" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""

# Get project root (where this script is)
$projectRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$envPath = Join-Path $projectRoot $envName

Write-Host "Project root: $projectRoot" -ForegroundColor Yellow
Write-Host "Environment path: $envPath" -ForegroundColor Yellow
Write-Host "QGIS profile: $profileName" -ForegroundColor Yellow
Write-Host ""

# Check if pyproject.toml exists
$pyprojectPath = Join-Path $projectRoot "pyproject.toml"
if (-not (Test-Path $pyprojectPath)) {
    Write-Host "ERROR: pyproject.toml not found at $pyprojectPath" -ForegroundColor Red
    exit 1
}

# Remove existing environment if it exists
if (Test-Path $envPath) {
    Write-Host "Removing existing environment at $envPath..." -ForegroundColor Yellow
    Remove-Item $envPath -Force -Recurse
}

# Create virtual environment
Write-Host "Creating virtual environment..." -ForegroundColor Cyan
python -m venv $envPath

if (-not $?) {
    Write-Host "ERROR: Failed to create virtual environment" -ForegroundColor Red
    Write-Host "Make sure Python 3.13+ is installed and in PATH" -ForegroundColor Red
    exit 1
}

# Activate environment
$activateScript = Join-Path $envPath "Scripts\Activate.ps1"
if (-not (Test-Path $activateScript)) {
    Write-Host "ERROR: Activate script not found at $activateScript" -ForegroundColor Red
    exit 1
}

Write-Host "Activating environment..." -ForegroundColor Cyan
& $activateScript

# Upgrade pip
Write-Host ""
Write-Host "Upgrading pip..." -ForegroundColor Cyan
python -m pip install --upgrade pip

# Parse dependencies from pyproject.toml and install
Write-Host ""
Write-Host "Installing dependencies from pyproject.toml..." -ForegroundColor Cyan
Write-Host ""

# Core dependencies (matching pyproject.toml exactly but with numpy 1.x for QGIS compatibility)
$dependencies = @(
    "numpy<2.0",  # Use numpy 1.x for compatibility
    "geopandas==1.1.1",
    "matplotlib>=3.10.8",
    "networkx==3.5",
    "pandas==2.3.1",
    "scipy>=1.16.3",
    "shapely>=2.1.2",
    "tqdm>=4.67.1",
    "PyQt5",  # QGIS uses PyQt5, not PyQt6
    "PyQt5-sip",
    "folium",
    "plotly",
    "pydantic",
    "mapclassify"
)

foreach ($dep in $dependencies) {
    Write-Host "Installing $dep..." -ForegroundColor White
    python -m pip install $dep
    if (-not $?) {
        Write-Host "WARNING: Failed to install $dep" -ForegroundColor Yellow
    }
}

# Create startup script for QGIS to add this environment to sys.path
$startupDir = "$env:APPDATA\QGIS\QGIS3\profiles\$profileName\python"
if (-not (Test-Path $startupDir)) {
    Write-Host ""
    Write-Host "Creating QGIS Python startup directory..." -ForegroundColor Cyan
    New-Item -ItemType Directory -Path $startupDir -Force | Out-Null
}

$startupScript = Join-Path $startupDir "startup_dcascade_env.py"
$sitePackages = Join-Path $envPath "Lib\site-packages"

$scriptContent = @"
# Auto-generated by setup_qgis_environment.ps1
# Adds Q-Cascade environment to QGIS Python path

import sys
import os

dcascade_env_path = r"$sitePackages"

    if dcascade_env_path not in sys.path:
    sys.path.insert(0, dcascade_env_path)
    print(f"Q-Cascade: Added environment to path: {dcascade_env_path}")
else:
    print(f"Q-Cascade: Environment already in path: {dcascade_env_path}")

# Verify critical imports
try:
    import numpy
    import pandas
    import geopandas
    import networkx
    print(f"Q-Cascade: Environment loaded successfully")
    print(f"  - numpy: {numpy.__version__}")
    print(f"  - pandas: {pandas.__version__}")
    print(f"  - geopandas: {geopandas.__version__}")
    print(f"  - networkx: {networkx.__version__}")
except ImportError as e:
    print(f"Q-Cascade: ERROR loading environment: {e}")
"@

Write-Host ""
Write-Host "Creating QGIS startup script..." -ForegroundColor Cyan
Set-Content -Path $startupScript -Value $scriptContent -Encoding UTF8

Write-Host ""
Write-Host "============================================" -ForegroundColor Green
Write-Host "Setup Complete!" -ForegroundColor Green
Write-Host "============================================" -ForegroundColor Green
Write-Host ""
Write-Host "Environment created at:" -ForegroundColor Cyan
Write-Host "  $envPath" -ForegroundColor White
Write-Host ""
Write-Host "QGIS startup script created at:" -ForegroundColor Cyan
Write-Host "  $startupScript" -ForegroundColor White
Write-Host ""
Write-Host "Installed packages:" -ForegroundColor Cyan
& python -m pip list
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "1. Restart QGIS with profile '$profileName'" -ForegroundColor White
Write-Host "2. Open Python Console in QGIS (Plugins > Python Console)" -ForegroundColor White
Write-Host "3. Check that the startup message appears showing numpy 1.x" -ForegroundColor White
Write-Host "4. Test: import numpy; print(numpy.__version__)" -ForegroundColor White
Write-Host ""
Write-Host "If issues persist:" -ForegroundColor Yellow
Write-Host "- Check QGIS Python Console for startup script output" -ForegroundColor White
Write-Host "- Verify numpy version in QGIS: import numpy; print(numpy.__version__)" -ForegroundColor White
Write-Host "- The startup script will run automatically when QGIS starts" -ForegroundColor White
Write-Host ""
